# Generated by Django 3.2.6 on 2021-08-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.CharField(blank=True, max_length=150, verbose_name='note'),
        ),
    ]
