# Generated by Django 3.2.6 on 2021-08-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SHOP', 'Shop'), ('BUYER', 'Buyer')], default='BUYER', max_length=5, verbose_name='user role'),
        ),
    ]
