# Generated by Django 3.2.6 on 2021-08-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('CART', 'cart'), ('NEW', 'new'), ('CONFIRMED', 'confirmed'), ('ASSEMBLED', 'assembled'), ('SENT', 'sent'), ('DELIVERED', 'delivered'), ('CANCELED', 'canceled')], default='CART', max_length=15, verbose_name='state'),
        ),
    ]
